---
date: 2021-03-25
categories: [first steps, quickstart]
image: https://images.unsplash.com/photo-1558395556-da76deb52b24
---

# First Steps with Julia

If you're looking to try out Julia, here's what we recommend as the first things you do.

:::{.callout-note}
- This post is compiled from the "First Steps" series that appeared in the original version of the Julia For Data Science newsletter.
- It has been updated and condensed for 2025.
:::

## Download Julia

To download Julia, use the instructions at [https://julialang.org/downloads](https://julialang.org/downloads).  For convenience, we'll repeat the installation method most people will use:


::: {.panel-tabset}

## Mac/Unix/Linux

- Copy/paste in terminal:

```bash
curl -fsSL https://install.julialang.org | sh
```

## Windows

- Copy/paste in Windows Command Prompt:

```cmd
winget install julia -s msstore
```
:::

The above command will install the [juliaup](https://github.com/JuliaLang/juliaup) installation manager for Julia.  This is generally recommended over a manual download since juliaup will let you know when new versions are available.


## Install Packages

- Julia has an amazing package manager: [Pkg](https://pkgdocs.julialang.org/v1/) (more on Pkg in a future post)
