project:
  type: website

website:
  title: "Julia for Data Science"
  site-url: http://juliafordatascience.com
  draft-mode: visible
  search:
    type: textbox
  navbar:
    background: light
    left:
      - about.qmd
    tools:
      - icon: rss
        href: /index.xml
      - icon: github
        href: https://github.com/joshday/juliafordatascience.com
      - icon: twitter
        href: https://twitter.com/JuliaForDataSci


format:
  html:
    code-copy: true
    mainfont: Inter
    lang: en
    code-line-numbers: true
    resources:
      - "assets/"
    theme: flatly
    css:
      - https://rsms.me/inter/inter.css
      # - https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css
      - assets/custom.css
    toc: true
